name: Check consistency of dist files
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dist_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
    - name: Install dependencies
      run: |
        npm ci
    - name: Build
      run:
        npm run build
    - name: Check
      run: |
        git diff dist/ | tee .git-diff-dist-check-result
        if [ -s .git-diff-dist-check-result ]; then
          echo "dist/ is not up-to-date. Please run 'npm run build' and commit the changes."
          exit 1
        fi
