name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Tag and create release ${{ inputs.version }}
      id: release
      uses: ./
      with:
        tag_name: ${{ inputs.version }}
        release_name: Release ${{ inputs.version }}
        discussion_category_name: 'Announcements'
        generate_release_notes: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
